source 'https://rubygems.org'

gem 'rails', '4.2.10'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'cocoon'
gem 'turbolinks'
gem 'jbuilder'
gem 'sdoc'

# Add manual
gem 'devise'
gem 'pundit'
gem 'sqlite3'
gem 'carrierwave'
gem 'rmagick'
gem 'audited'
gem 'ransack'
#gem 'thin'
# Bug dentro de params
gem 'impressionist'
# group :production do 
#   gem 'pg', '~> 0.15'
# end
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'

group :development, :test do
  #gem 'byebug'
  #gem 'sqlite3'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :development do
  gem 'web-console'
  gem 'spring'
end